elastic/golang-crossbuild

README.md

Use `-e` flag to set an environment variable in the container.

[doc] Fix example command

---

go1.11/darwin/Dockerfile

required as of go1.11.   This also changes our SDK to a self-bundled version generated with `gen_sdk_package.sh` from osxcross that include c++ headers.
closes #6

use Mac OS 10.10 for darwin build

---

fpm/Makefile

Previous version of FPM did not pin to a specific version of
childprocess.
See for details https://github.com/jordansissel/fpm/issues/1592

update to FPM 1.11.0

---

go1.10/base/Dockerfile.tmpl
go1.10/base/sources-debian8.list
go1.11/base/Dockerfile.tmpl
go1.11/base/sources-debian8.list

Follow on to #16. At the time of that change Jessie was still working,
now it's not.

Update sources.list for Debian 8

---

go1.10/base/sources-debian7.list
go1.11/base/sources-debian7.list

Move the security repository to archive.

Fix missing debian source repository

---

Makefile

Just build fpm out of the target loop, so we don't have to check if the `Makefile.debian*` exists, since we rarely change fpm we should build it often.

Fix the fpm targets

---

fpm/Dockerfile.tmpl

stable changed to buster and buster included a newer rpm package and now
the rpmbuild is including files like
/usr/lib/.build-id/9d/3614c9a48200641b24890671bea43ef43c760b
in our packages. So we'll base this image on stretch and then update
all the things using the container to include
--rpm-rpmbuild-define "_build_id_links none"
when building RPMs to prevent those files from being included. Then
we can update.
https://github.com/jordansissel/fpm/issues/1503

Pin parent image to stretch rather than stable

---

README.md
go1.11/Makefile.common
go1.11/base/Dockerfile.tmpl
go1.12/Makefile.common
go1.12/base/Dockerfile.tmpl

Includes security fixes to the net/http and net/url packages.

Update to Go 1.11.13, 1.12.8

---

README.md
go1.12/Makefile.common
go1.12/base/Dockerfile.tmpl

This release includes fixes to the linker, and the os and math/big packages.

Update Go to 1.12.9

---

README.md
go1.13/Makefile.common
go1.13/base/Dockerfile.tmpl

go1.13.5 (released 2019/12/04) includes fixes to the go command, the runtime, the linker, and the net/http package.

Update Go to 1.13.5

---

README.md
go1.13/Makefile.common
go1.13/base/Dockerfile.tmpl

go1.13.6 (released 2020/01/09) includes fixes to the runtime and the net/http package.

Update Go to 1.13.6

---

README.md
go1.13/Makefile.common
go1.13/base/Dockerfile.tmpl

go1.13.7 (released 2020/01/28) includes two security fixes to the crypto/x509 package. See the Go 1.13.7 [milestone](url) on the issue tracker for details.

Update Go to 1.13.7

---

README.md
go1.13/Makefile.common
go1.13/base/Dockerfile.tmpl

go1.13.8 (released 2020/02/12) includes fixes to the runtime, the crypto/x509, and net/http packages.

Update Go to 1.13.8

---

README.md
go1.13/Makefile.common
go1.13/base/Dockerfile.tmpl
go1.14/Makefile.common
go1.14/base/Dockerfile.tmpl

go1.14.2 (released 2020/04/08) includes fixes to cgo, the go command, the runtime, os/exec, and testing packages.
go1.13.10 (released 2020/04/08) includes fixes to the go command, the runtime, os/exec, and time packages.

Update Go to 1.13.10, 1.14.2

---

README.md
go1.13/Makefile.common
go1.13/base/Dockerfile.tmpl
go1.14/Makefile.common
go1.14/base/Dockerfile.tmpl

go1.13.12 (released 2020/06/01) includes fixes to the runtime, and the go/types and math/big packages.
go1.14.4 (released 2020/06/01) includes fixes to the go doc command, the runtime, and the encoding/json and os packages.

Update to go 1.13.12, 1.14.4

---

Jenkinsfile
Makefile.common
README.md
fpm/Makefile

Enable CI pipeline to build and push the docker images.
The push event works for:
- everything (branches, tags, PRs) and will push them in https://docker.elastic.co:7000/observability-ci/golang-crossbuild:<VERSION><SUFFIX> 
- on master based to the default location set in the Makefile.
- `REPOSITORY=docker.elastic.co/observability-ci make build`
```
$ docker images | grep observability-ci            
docker.elastic.co/observability-ci/fpm                      1.11.0                 1fbf2b9b5555        2 minutes ago       416MB
docker.elastic.co/observability-ci/golang-crossbuild        1.14.4-main-debian8    51fbb901cd8a        2 minutes ago       1.39GB
docker.elastic.co/observability-ci/golang-crossbuild        1.14.4-main-debian7    3c5321b6f233        2 minutes ago       1.01GB …
```

[CI]: CI pipeline

---

go1.13/Makefile.common

set the tag to the same Go version we use in Beats

fix: user the same version tag than Go in Beats

---

go1.14/Makefile.common
go1.14/base/Dockerfile.tmpl

fix: bump go version to 1.14.6

---

.gitignore
Makefile

Populate the error level in the foreach, for such I use a file flag with the errorlevel since I could not find the way to use dynamic variables within the make target.
As far as I see the CI uses the toplevel Makefile:
- build
- push
Those goals call the other makefiles which already contain the `exit 1` if something bad happened (https://github.com/elastic/golang-crossbuild/blob/7fe9c7c0bcde40f473473271f8b807557d74c683/go1.14/Makefile.debian7#L8) but it seems they are not populated as expected
For instance:
```bash
curl -s 'https://beats-ci.elastic.co/job/Beats/job/golang-crossbuild-mbp/view/change-requests/job/PR-68/1/consoleText'  | grep failed                                                                                        
[2020-11-09T15:26:26.723Z] ../Makefile.common:13: …
```

Populate errorlevel from the top level Makefile

---

Jenkinsfile

Use the `arm` label to speed up the builds since it's not required anymore to use a fixed worker
We could not use labels as long as the package that causes docker login issues, (see https://github.com/docker/compose/issues/6023#issuecomment-402067570) were not removed for all the ARM workers

[CI] use label instead a fixed worker

---

go1.16/base/Dockerfile.tmpl

Python 3 is not a transitive dependency of any installed package so we have to explicitly install it.
closes https://github.com/elastic/golang-crossbuild/issues/92

fix: force to install Python 3

---

go1.16/arm/Dockerfile.tmpl
go1.16/armel/Dockerfile.tmpl
go1.16/armhf/Dockerfile.tmpl
go1.16/base-arm/Dockerfile.tmpl
go1.16/base/Dockerfile.tmpl
go1.16/main/Dockerfile.tmpl
go1.16/mips/Dockerfile.tmpl
go1.16/mips32/Dockerfile.tmpl
go1.16/ppc/Dockerfile.tmpl
go1.16/ppc/rootfs/compilers.yaml
go1.16/s390x/Dockerfile.tmpl

This PR adds a precompiled version of the libpcap library for each architecture, it requires changes in Beats to use the new precompile libraries. Some architectures that share Docker images have to use a different folder for the library to avoid conflicts. 
* arm64 - /libpcap/libpcap-1.8.1
* armel - /libpcap/libpcap-1.8.1
* armhf - /libpcap/libpcap-1.8.1
* base-arm - /libpcap/libpcap-1.8.1
* i386 - /libpcap/libpcap-1.8.1-i386
* win64 - /libpcap/win/WpdPack
* amd64 - /libpcap/libpcap-1.8.1-amd64
* mips64 - /libpcap/libpcap-1.8.1-mips64
* mips64el - /libpcap/libpcap-1.8.1-mips64el
* mips - /libpcap/libpcap-1.8.1-mips
* mispel - /libpcap/libpcap-1.8.1-mipsel
* ppc64 - /libpcap/libpcap-1.8.1-ppc64
* ppc64el - /libpcap/libpcap-1.8.1-mmpc64el
* s390x -- /libpcap/libpcap-1.8.1
```
git clone …
```

feta: precompile libpcap

---

Jenkinsfile
go1.15/main/rootfs/compilers.yaml
go1.16/Makefile.debian10
go1.16/base/Dockerfile.tmpl
go1.16/darwin-arm64/Dockerfile.tmpl
go1.16/darwin-arm64/Makefile
go1.16/darwin-arm64/rootfs/compilers.yaml
go1.16/darwin-arm64/rootfs/helloWorld.c
go1.16/darwin/Dockerfile.tmpl

This PR adds support for compile binaries for darwin/arm64, it compiles clang and LLVM before compiling [osxcross](https://github.com/tpoechtrager/osxcross) this takes a few hours but at the moment the version of clang and LLVM provided by Debian does not support this architecture.
it does not support darwin/arm64e it requires to use [apple's LLVM fork](https://github.com/apple/llvm-project) 
https://stackoverflow.com/questions/52624308/xcode-arm64-vs-arm64e
other changes in this PR:
* chore: set OSX_VERSION_MIN to 10.10 on SDK 10.14
* chore: do not install python on Debian 10 is installed
* chore: remove compilers no available in main 
* feat: list Docker images
* chore: pipeline increase timeout
related to https://github.com/elastic/golang-crossbuild/issues/94

feat: add suport for darwin/arm64

---

go1.15/arm/Dockerfile.tmpl
go1.15/armel/Dockerfile.tmpl
go1.15/armhf/Dockerfile.tmpl
go1.16/arm/Dockerfile.tmpl
go1.16/armel/Dockerfile.tmpl
go1.16/armhf/Dockerfile.tmpl

In some architectures the libpcap configure does not find the correct gcc to use so it uses gcc generating x86_64 binaries, those binaries are not valid for other architectures. This PR force the configure to use the right gcc for each architecture.
related to https://github.com/elastic/golang-crossbuild/issues/63 https://github.com/elastic/beats/pull/25769

fix: force gcc to build libpcap

---

go1.15/base-arm/Dockerfile.tmpl
go1.15/base/Dockerfile.tmpl
go1.16/base-arm/Dockerfile.tmpl
go1.16/base/Dockerfile.tmpl

Update patch versions to 1.16.5 and 1.15.13
- Relates https://github.com/elastic/beats/issues/25346

Update patch version of golang

---

.ci/bump-go-release-version.sh
.gitignore
.mergify.yml

I used https://github.com/elastic/golang-crossbuild/pull/106 and https://github.com/elastic/golang-crossbuild/pull/107 as the references for the implementation.
It only supports the latest existing minor version, `1.16` at the moment.
For a bump of minor versions, the automation does not work yet, since it requires some other actions:
- Create the `go1.17` folder structure with its files
- Update the README.md
- Remove `go1.15` folder
You can use this script locally:
```bash
.ci/bump-go-release-version.sh <new-go-version>
```
NOTE: it will add and commit the changes in the existing branch. The push and PR creation is not done within this script.
No more manual actions.
This automation will not merge the PR automatically. We do want the teams to do so:
- Review the changes and validate the …

Bump golang version with the latest supported one

---

Jenkinsfile
go1.16/Makefile.common
go1.16/base-arm/Dockerfile.tmpl
go1.16/base/Dockerfile.tmpl

[automation] Update go release version 1.16.6

---

Jenkinsfile
go1.15/Makefile.common
go1.15/base-arm/Dockerfile.tmpl
go1.15/base/Dockerfile.tmpl

What
Bump go release version with the latest release.
Further details
1.15.14

[Automation] Update go release version to 1.15.14

---

fpm/Dockerfile.tmpl
fpm/Makefile

This updates the FPM image to include 1.13.1. And it updates the
base image to debian:buster which has a newer version of RPM that
supports sha256 digests.
RPM version 4.14.2.1
1.13.1

Update FPM to 1.13.1

---

Jenkinsfile
go1.16/Makefile.common
go1.16/base-arm/Dockerfile.tmpl
go1.16/base/Dockerfile.tmpl

[automation] Update go release version 1.16.7

---

README.md

Use a table format for the docker tags.
Update docker tags with their relevant tags.
Update golang versions.
Add 1.17 version
Closes https://github.com/elastic/golang-crossbuild/issues/121

[docs] update supported golang versions and docker tags

---

Jenkinsfile

Enable https://github.com/elastic/apm-pipeline-library/tree/master/vars#stagestatuscache to allow rebuilding the CI build for the same commit.
This particular pipeline does build and push docker images, it takes a bit of time, and could happen that some third-party networking was not accessible, so rather than building from scratch everything let's use `stageStatusCache` to actually rebuild what's needed.

CI: allow caching to rebuild if needed

---

go1.16/main/Dockerfile.tmpl
go1.17/main/Dockerfile.tmpl

Use the google storage bucket to download `WpdPack_4_1_2.zip` from.
Avoid CA certificate issues and reduce the need of a third party system while the google storage bucket is already something we have put in place for some other binaries.

internal: use google storage bucket for WpdPack_4_1_2.zip

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[automation] Update go release version 1.17.2

---

.ci/scripts/release-notes.sh
.grenrc.js
Jenkinsfile
README.md

Update the docker build tags:
- for Golang >= 1.16 
- Until Golang <= 1.15
Automate the changelog generation in the GitHub release section
I generated locally the Changelog for testing purposes:
```bash
gren changelog --generate --override --token="${GREN_GITHUB_TOKEN}" -c .grenrc.js --username=elastic
🤖  - Generate changelog file:
===================================
✔ Releases found: 3
✔ Tags found: 1.17.2, 1.17.1
✔ Pull Requests found: 2
✔ Changelog created in /Users/vmartinez/work/src/github.com/elastic/golang-crossbuild/CHANGELOG.md
```
Requires https://github.com/elastic/apm-pipeline-library/pull/1341

release: automate changelog generation

---

Jenkinsfile
go1.16/mips/Dockerfile.tmpl
go1.16/mips32/Dockerfile.tmpl
go1.16/ppc/Dockerfile.tmpl
go1.16/s390x/Dockerfile.tmpl
go1.17/mips/Dockerfile.tmpl
go1.17/mips32/Dockerfile.tmpl
go1.17/ppc/Dockerfile.tmpl
go1.17/s390x/Dockerfile.tmpl

- Use top-level post-release stage rather than multiple post-release stages, since it's one task per release.
- Fix missing dependencies for the mips, ppc, s390x arch.
- Use https://github.com/elastic/apm-pipeline-library/pull/1341

fix missing deps for librpmio3 and post-release stage in the pipeline

---

Jenkinsfile
go1.16/Makefile.common
go1.16/base-arm/Dockerfile.tmpl
go1.16/base/Dockerfile.tmpl

Bump go 1.16.9
I'm not sure if we should maintain this but just in case

[Automation] Update go release version to 1.16.9

---

.ci/scripts/gren
Jenkinsfile

Some leftovers regarding the bump automation that were not updated! 
In addition, `gren` was not in the path

Release: enable gren in the PATH and bump go version

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[automation] Update go release version 1.17.3

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[Automation] Update go release version to 1.17.4

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[automation] Update go release version 1.17.5

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[automation] Update go release version 1.17.6

---

Jenkinsfile
Makefile
Makefile.common
go1.16/Makefile.common
go1.17/Makefile.common

For some reason the toplevel Makefile did not copy in each go.1x folder the npcap but in the first one.
This will move the logic in each makefile

fix copy npcap

---

go1.17/main/Dockerfile.tmpl

Need to be able to extract the a file from .MSI distro for osquerybeat. 
The current workaround is installing msitools during osquerybeat build time for window platform.
Including this into the builder image would allow us to remove the workaround.
Closes: https://github.com/elastic/beats/issues/29826
Screenshot verifying the local image build msiextract tool is installed with this change:

Add msitools to docker beats golang-crossbuild 1.17 main image

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[automation] Update go release version 1.17.7

---

Jenkinsfile

Merge the `build` and `staging` stages and use GitHub checks to notify if any failure.
Reduce the changes of rebuilding to be able to retag the images.

ci: simplify stages

---

Jenkinsfile
go1.17/Makefile.common
go1.17/base-arm/Dockerfile.tmpl
go1.17/base/Dockerfile.tmpl

[automation] Update go release version 1.17.8

---

Jenkinsfile

Support branches for active Golang versions
This project is not anymore mono-branch but it follows the branch strategy based on the Major.Minor Golang versions

ci: release for 1.x branches

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18+label%3ACherryPickApproved) for 1.18

[automation] Update go release version 1.18

---

go/Makefile
go/Makefile.debian9

Remove support for Debian 9 on mips mips32 ppc s390x. Recent changes on the `librpm-dev` package in Debian 9 have broken the way we install this library for cross compile, due to we have support on Debian 10 that works fine for those architectures we remove support for them on Debian 9.
closes https://github.com/elastic/golang-crossbuild/issues/173

fix: remove support for debian 9 on mips mips32 ppc s390x

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.17.9+label%3ACherryPickApproved) for 1.17.9

[automation] Update go release version 1.17.9

---

README.md

As agreed in https://github.com/elastic/golang-crossbuild/issues/173 some platforms are not anymore supported for `Debian9` but `Debian10` instead.

docs: debian 10 support only for some platforms

---

.ci/llvm-apple.groovy

Only Debian 10 is supported, LLVM needs Python installed

fix: add TAG_EXTENSION to use the right base images

---

Jenkinsfile
Makefile
go/Makefile.debian11
go/arm/Dockerfile.tmpl
go/armel/Dockerfile.tmpl
go/armhf/Dockerfile.tmpl
go/base/Dockerfile.tmpl
go/base/sources-debian11.list
go/darwin-arm64/Dockerfile.tmpl
go/darwin/Dockerfile.tmpl
go/main/Dockerfile.tmpl
go/mips/Dockerfile.tmpl
go/mips32/Dockerfile.tmpl
go/ppc/Dockerfile.tmpl
go/s390x/Dockerfile.tmpl

Add support for `Debian 11`
Some packages are not available for `mips` in `bullseye`, so I removed them from the list of supported platforms for Debian 11.
https://packages.debian.org/bullseye/libc6-dev is the package that failed to be found
Closes https://github.com/elastic/golang-crossbuild/issues/178

Support Debian 11

---

.ci/jobs/fpm-mbp.yml
.ci/jobs/golang-crossbuild-mbp.yml
.ci/jobs/llvm-apple-mbp.yml

Current active branches:
* https://github.com/elastic/golang-crossbuild/tree/main
* https://github.com/elastic/golang-crossbuild/tree/1.16
* https://github.com/elastic/golang-crossbuild/tree/1.17
* https://github.com/elastic/golang-crossbuild/tree/1.17.5.x

jjbb: build go version branches (major.minor)

---

.ci/llvm-apple.groovy
go/llvm-apple/Makefile

The Go version is not relevant for the LLVM Docker image, it only depends on the Debian version we are using.

chore: remove Go version from the LLVM image tag

---

go/darwin-arm64/Dockerfile.tmpl
go/darwin/Dockerfile.tmpl

This PR adds support for darwin/arm64e architecture. To do that it compiles [Apple's LLVM](https://github.com/apple/llvm-project) then compiles [osxcross](https://github.com/tpoechtrager/osxcross). It takes about 3h to build the image.
depends on https://github.com/elastic/golang-crossbuild/pull/182

feat: support for darwin/arm64e

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.17.10+label%3ACherryPickApproved) for 1.17.10

[automation] Update go release version 1.17.10

---

go/base/Dockerfile.tmpl

Binary utilities that support multi-arch targets
The programs in this package are used to manipulate binary and object files that may have been created on other architectures. This package is primarily for multi-architecture developers and cross-compilers and is not needed by normal users or developers. Note that a cross-assembling version of gas is not included in this package, just the binary utilities.

feat: add binutils-mutiarch

---

.ci/scripts/buildx.sh
Jenkinsfile
Makefile.common
go/Makefile.common
go/base/Dockerfile.tmpl
go/base/Makefile
go/base/install-go.sh

it builds the base image for linux/amd64 and linux/arm64, the push is delegated to buildx, this push the manifest for the two platforms 

feat: build multiarch Docker images

---

.ci/bump-go-release-version.sh
go/base/install-go.sh

Since https://github.com/elastic/golang-crossbuild/blob/main/go/base/install-go.sh has been added then the bump automation should be changed
Given `1.18.2` then
```diff
diff --git a/Jenkinsfile b/Jenkinsfile
index 4abab22..ccda557 100644
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -29,7 +29,7 @@ pipeline {
DOCKER_REGISTRY_SECRET = 'secret/observability-team/ci/docker-registry/prod'
DOCKER_REGISTRY = 'docker.elastic.co'
STAGING_IMAGE = "${env.DOCKER_REGISTRY}/observability-ci"
-    GO_VERSION = '1.18.1'
+    GO_VERSION = '1.18.2'
BUILDX = "1"
}
options {
diff --git a/go/Makefile.common b/go/Makefile.common
index 66499eb..2ce4ad9 100644
--- a/go/Makefile.common
+++ b/go/Makefile.common
@@ -2,7 +2,7 @@ SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
include $(SELF_DIR)/../Makefile.common
NAME …
```

fix auto-bump

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.2+label%3ACherryPickApproved) for 1.18.2

[automation] Update go release version 1.18.2

---

.ci/llvm-apple.groovy
.ci/scripts/buildx.sh
go/llvm-apple/Dockerfile.tmpl
go/llvm-apple/Makefile
go/llvm-apple/lcxx.patch

build amd64/amr64 LLVM Docker images
depends on https://github.com/elastic/golang-crossbuild/pull/197

feat: build amd64/arm64 LLVM Docker images

---

.gitignore
go/darwin-arm64/Dockerfile.tmpl
go/darwin-arm64/Makefile
go/darwin/Dockerfile.tmpl
go/darwin/Makefile

build darwin amd64/arm64 Docker images
depends on https://github.com/elastic/golang-crossbuild/pull/197

feat: build darwin amd64/arm64 Docker images

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.3+label%3ACherryPickApproved) for 1.18.3

[automation] Update go release version 1.18.3

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.4+label%3ACherryPickApproved) for 1.18.4

[automation] Update go release version 1.18.4

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.5+label%3ACherryPickApproved) for 1.18.5

[automation] Update go release version 1.18.5

---

README.md
go/Makefile.debian10
go/Makefile.debian11

Remove support for `Debian 10` on `armel`, `mips`, `mips32`, `ppc` and `s390x`. Recent changes on the `librpm-dev` package in `Debian 10` have broken the way we install this library for cross compile, due to we have support on `Debian 11` that works fine for those architectures (but `mips32`) we remove support for them on `Debian 10`.
Some packages for `mips32` are not available in `Debian 11` therefore 
https://packages.debian.org/bullseye/libc6-dev
vs
`Debian 10`
https://packages.debian.org/buster/libc6-dev
Similar to https://github.com/elastic/golang-crossbuild/pull/175
Closes https://github.com/elastic/golang-crossbuild/issues/224

fix: remove support for Debian 10 on armel, mips, mips32, ppc and s390x

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.6+label%3ACherryPickApproved) for 1.18.6

[automation] Update go release version 1.18.6

---

.ci/bump-go-release-version.sh

Support major.minor in addition to major.minor.patch
When bumping from 1.18.x to 1.19, the very first version for 1.19 does not have any patch version. Hence the automation for bumping 1.19.1 wont' work since it looks for `major.minor.patch` in the replacement
`.ci/bump-go-release-version.sh 1.19.1`
produced
```diff
diff --git a/Jenkinsfile b/Jenkinsfile
index 0795d17..111508e 100644
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -29,7 +29,7 @@ pipeline {
DOCKER_REGISTRY_SECRET = 'secret/observability-team/ci/docker-registry/prod'
DOCKER_REGISTRY = 'docker.elastic.co'
STAGING_IMAGE = "${env.DOCKER_REGISTRY}/observability-ci"
-    GO_VERSION = '1.19'
+    GO_VERSION = '1.19.1'
BUILDX = "1"
}
options {
diff --git a/go/Makefile.common b/go/Makefile.common
index 222f25b..137dfe8 100644
--- …
```

fix: support major.minor in addition to major.minor.patch

---

NPCAP.md

Update the docs so it's clear what's the Google project to be used when uploading the artifacts to the google bucket.
Thanks @efd6 for going through this and find this missing bit of configuration.

docs: access to the google storage bucket

---

NPCAP.md

Add a note so future people do not fail to add back ports when bumping Npcap version.
Please take a look.

docs: add note to make sure back ports are added

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.7+label%3ACherryPickApproved) for 1.18.7

[automation] Update go release version 1.18.7

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.19.2+label%3ACherryPickApproved) for 1.19.2

[automation] Update go release version 1.19.2

---

go/base/Dockerfile.tmpl

Debian 11 fails when installing the dependency libc6 since it requires a downgraded version instead. 
Closes https://github.com/elastic/golang-crossbuild/issues/245

fix libc6-dev : Depends: libc6 (= 2.31-13+deb11u4) but 2.31-13+deb11u5

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.19.3+label%3ACherryPickApproved) for 1.19.3

[automation] Update go release version 1.19.3

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.18.8+label%3ACherryPickApproved) for 1.18.8

[automation] Update go release version 1.18.8

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.19.4+label%3ACherryPickApproved) for 1.19.4

[automation] Update go release version 1.19.4

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.20+label%3ACherryPickApproved) for 1.20

[automation] Update go release version 1.20

---

.ci/bump-go-release-version.sh
.ci/bump-golang.yml
.github/workflows/bump-golang-1.18.yml
.github/workflows/bump-golang-1.19.yml
.github/workflows/bump-golang.yml
.github/workflows/bump-golang/action.yml

Automate the golang bump within the project itself using [updatecli](https://www.updatecli.io/) and github actions
Remove the dependency with Jenkins and the definition of what to do in [apm-pipeline-library](https://github.com/elastic/apm-pipeline-library/blob/a3850732518748f2e71815c093d58cb071d0d8a3/.ci/.bump-go-release-version.yml#L33-L40)
Use updatecli that provides the tooling for bumping versions
There will be one GitHub workflow per active Golang minor version.

automate bump golang version

---

.ci/bump-golang.yml

Shell actions in `updatecli` require some specific implementation see https://www.updatecli.io/docs/plugins/resource/shell/#_shell_target
Hence, the condition will ensure no changes need to be applied in the latest release matches the one in the file `go/Makefile.common`.
Fixes https://github.com/elastic/golang-crossbuild/issues/265

updatecli: use condition to fix shell action idempotence

---

.ci/bump-golang.yml

fixes https://github.com/elastic/golang-crossbuild/issues/265
Unfortunately https://github.com/elastic/golang-crossbuild/pull/266 didn't work as expected

updatecli: use file for the condition

---

.ci/bump-golang.yml
.mergify.yml

When we added the `updatecli` the mergify automation was not changed accordingly, hence the branches are piled up.

mergify/updatecli: delete branches and add changelog URL

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.19.9+label%3ACherryPickApproved) for 1.19.9
---
<Actions>
<action id="a2eed144b6902b032e560793ed0c72992600b77bc474940defb0a6b344a4521c">
<h3>Bump golang-version to latest version</h3>
<details id="226c7073ca2786d439fbbe0bf13d2b5523040d4801dfca93d49ece1280917dd3">
<summary>Update go version 1.19.9</summary>
<details>
<summary>1.19.9</summary>
<pre>no GitHub Release found for go1.19.9 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
</action>
</Actions>
---
<details><summary>Updatecli options</summary>
Most of Updatecli configuration is done via Updatecli manifest.
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this …

[Automation] Bump Golang version to 1.19.9

---

.ci/llvm-apple.groovy
.github/release-drafter.yml
Jenkinsfile
Makefile
README.md
go/Makefile.debian12
go/arm/Dockerfile.tmpl
go/armel/Dockerfile.tmpl
go/armhf/Dockerfile.tmpl
go/base/Dockerfile.tmpl
go/base/sources-debian12.list
go/darwin-arm64/Dockerfile.tmpl
go/darwin/Dockerfile.tmpl
go/llvm-apple/Dockerfile.tmpl
go/main/Dockerfile.tmpl
go/mips/Dockerfile.tmpl
go/mips32/Dockerfile.tmpl
go/ppc/Dockerfile.tmpl
go/s390x/Dockerfile.tmpl

Does what it says in the tin.
`Debian 12` has been released early June 2023: https://www.debian.org/News/2023/20230610
Requires https://github.com/debuerreotype/docker-debian-artifacts/issues/196
`Debian 12` is needed to be added in some of the Dockerfile templates so the packages are installed for that particular version. For such, I looked for `debian 11` and added the condition for `debian 12`
llvm for `Debian 12` is also required, hence [llvm-apple-mbp](https://beats-ci.elastic.co/job/golang-crossbuild/job/llvm-apple-mbp/) needs to be triggered too.
llvm for `Debian 12` failed with some missing imports, see https://reviews.llvm.org/D89450 and https://github.com/elastic/golang-crossbuild/pull/298#issuecomment-1589596842, so it was required to bump the version for …

enable Debian 12 and bump llvm version to swift-5.6.3 

---

.github/release-drafter.yml
README.md

Closes https://github.com/elastic/golang-crossbuild/issues/295
Release Drafter and REAMDE.md will include the name of the docker images for the different Debian versions supported.

release notes: add docker image suffixes

---

.github/release-drafter.yml
README.md

Even though if they are built they are not supported. So for the time being this will help consumers so they know what to expect when using the unsupported win32 platform.
part of https://github.com/elastic/golang-crossbuild/issues/231

docs: remove windows 32 references

---

Jenkinsfile
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/install-go.sh

See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.19.12+label%3ACherryPickApproved) for 1.19.12
---
<Actions>
<action id="428fe48e5a6b8b833823486196c9f76dcadda8bee0014ac56d8d16249ae4475c">
<h3>Bump golang-version to latest version</h3>
<details id="226c7073ca2786d439fbbe0bf13d2b5523040d4801dfca93d49ece1280917dd3">
<summary>Update go version 1.19.12</summary>
<p>ran shell command &#34;.ci/bump-go-release-version.sh 1.19.12&#34;</p>
<details>
<summary>1.19.12</summary>
<pre>no GitHub Release found for go1.19.12 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p>
<details><summary>Options:</summary>
<br /> …

[Automation] Bump Golang version to 1.19.12

---

go/arm/Dockerfile.tmpl
go/base/sources-debian11.list
go/main/Dockerfile.tmpl

A week ago Debian:11.7 was updated. Now it has preinstalled `libsystemd0:247.3-7+deb11u4`. `libsystemd-dev` requires  `libsystemd0` to be preinstalled and to have exactly same version as with specific version `libsystemd-dev`. 
`libsystemd-dev247.3-7+deb11u4` is not yet in the `bullseye` repository and the PR adds `bullseye-updates` to the `sources.list` and now we install the specified `libsystemd-dev247.3-7+deb11u4` for `Debian:11`

Fix debian 11 arm and main docker build

---

NPCAP.md

Trying to explain in the existing docs how the ncap could be backported to an existing golang-crossbuild version.
https://github.com/elastic/golang-crossbuild/pull/315#issuecomment-1723228820 is the one explaining these steps tool.

docs: how to backport ncap to an existing golang-crossbuild version

---

.buildkite/fpm-pipeline.yml
.buildkite/llvm-apple-pipeline.yml
catalog-info.yaml

In scope of [1695](https://github.com/elastic/ingest-dev/issues/1695) added pipelines for "LLVM - apple version" and "FPM - packaging made simple" pipelines

Added pipelines for llvm-apple and fpm

---

.buildkite/pull-requests.json

In scope of [1695](https://github.com/elastic/ingest-dev/issues/1695) added llvm-apple and fpm pipelines to execute in Buildkite

Updated pull-requests.json with llvm-apple & fpm pipelines

---

catalog-info.yaml

otherwise, there are no builds for the `1.20` branch
`v1.*` are tags.

bk: run for 1.x branches

---

.github/workflows/bump-golang-previous.yml
.github/workflows/bump-golang.yml
.github/workflows/opentelemetry.yml
README.md

This should help with explaining how to update the auto-bump automation, implemented in https://github.com/elastic/golang-crossbuild/pull/262,  when a new Golang version is released.
`1.20` was created with https://github.com/elastic/golang-crossbuild/pull/310

docs: explain how to update the auto-bump

---

.buildkite/bump-golang.yml
.github/workflows/bump-golang-previous.yml
.github/workflows/bump-golang.yml
.github/workflows/bump-golang/action.yml

* Notifications are not honoured since they should be declared in the composite action instead. See https://github.com/elastic/golang-crossbuild/pull/367; that was the initial attempt to change the notifications.
* updatecli is not honouring the condition when using the file kind. Let's use the shell kind with the grep command instead. See https://github.com/updatecli/updatecli/issues/1849

action: honour the right parameters for notifying and fix condition

---

go/Makefile.common
go/npcap/Dockerfile.tmpl

Make the Dockerfile COPY command fail when the npcap-oem.exe file is not present. This will prevent the npcap image variant from being released without it containing the installer.
Relates #381

Make npcap image build fail if installer is not present

---

Makefile.common

`1.79` release caused a problem: the `npcap-1.79.exe` was missing and broken images were published despite of that. 
Now it will stop building process if the required file is missing.

[CI] Abort image building process if the npcap file non found

---

Makefile.common
NPCAP.md

Modify the documentation and Makefile.common to reflect the GCS bucket name that CI will be depending upon to hold the npcap installer exe.
Relates #381

Change GCS bucket from obs-ci-cache to ingest-buildkite-ci

---

.buildkite/bump-go-release-version.sh

The bump automation does not work when there is a need to support three major versions.
https://golang.org/dl/\?mode\=json only reports the last two major versions.
This is a corner case, and I've never seen this issue in the past 🤔  
This should help with an invalid PR with empty sha256 values; see https://github.com/elastic/golang-crossbuild/pull/389/commits/d0af04f97a2381630ea5e8da5a99f50cf27856a0

automation: support EOL bump automation

---

.github/actions/bump-golang/action.yml
.github/workflows/bump-golang-previous.yml
.github/workflows/bump-golang.yml

Use GitHub secrets and remove the need to use the `elastic/apm-pipeline-library` in conjunction with the VAULT_ADDR.
This will help reducing the need of accessing vault but using the GitHub secrets for the slack bot notifications.
Since this project uses Buildkite, we can commit/push using the github-bot actor.
I tested this branch in https://github.com/elastic/golang-crossbuild/actions/runs/9180918975/job/25246450161 and it worked fine

github-actions: use github secrets for updatecli

---

.github/actions/bump-golang/action.yml

Reverts elastic/golang-crossbuild#427
Latest updatecli version bump causes issues (probably related to what's described in https://github.com/updatecli/updatecli/pull/2388).
This commit reverts to an older version of updatecli-action as done in other repos e.g. https://github.com/elastic/elastic-package/pull/2005

Revert "build(deps): bump updatecli/updatecli-action from 2.64.0 to 2.65.0 in /.github/actions/bump-golang in the github-actions group"

---

.github/actions/bump-golang/action.yml
.github/updatecli.d/bump-golang.yml
.github/workflows/bump-golang.yml

For some reason something is not right anymore
```
⚠ - 1 file(s) updated with "1.22.6":
* go/Makefile.common
ERROR: non-fast-forward update
ERROR: push error: authentication required
```
I saw we could pass the username when interacting with [github](https://www.updatecli.io/docs/plugins/scm/github/)
And this solved the issue, see https://github.com/v1v/golang-crossbuild/pull/1 that verified the changes for this PR.
Maybe something has changed in the GitHub API internals?

updatecli: set username

---

.github/updatecli.d/bump-go-release-version.sh
README.md
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

Requires https://github.com/elastic/golang-crossbuild/pull/435
Then we can branch off `main` and
Merge this PR.
Steps explained in https://github.com/elastic/golang-crossbuild#releasing-images-for-a-new-go-version
- Bump version.
- Remove `install-go.sh` and use native dockerfile commands to install golang for x86 - that's the case for ARM.
- Update bump automation to avoid bumping changes in `install-go.sh`
- Update docs.
@kruskall , do you mind adding some notes regarding the changes you did to fix the below two issues:
- `can't start telemetry child process: fork/exec /usr/local/go/bin/go: invalid argument`
- `go: error obtaining buildID for go tool compile: fork/exec /usr/local/go/pkg/tool/linux_arm64/compile: invalid argument`

Update to Go 1.23.0

---

.github/release-drafter.yml
README.md
go/Makefile.debian11
go/Makefile.debian9

Remove support for `Debian 10` on `armel`, `mips`, `ppc` and `s390x`. Recent changes on the `libsystem-dev` package in `Debian 11` have broken the way we install this library, due to we have support on `Debian 12` that works fine for those architectures we remove support for them on `Debian 11`.
Similar to https://github.com/elastic/golang-crossbuild/pull/175
Similar to https://github.com/elastic/golang-crossbuild/pull/225
Closes https://github.com/elastic/golang-crossbuild/issues/444

Fix: remove support for debian 11 on armel, mips, ppc and s390x

---

.github/workflows/bump-golang-previous.yml

Since `1.22` was transitioned to a maintenance branch from `main`, `main` is now pointing to `1.23`. This is required 
A leftover from https://github.com/elastic/golang-crossbuild/pull/436

ci: support previous minor 1.22

---

.mergify.yml
README.md

mergify: add backport-v1.22

---

.buildkite/pull-requests.json

Skip CI when only unrelated changes are made.
Closes: https://github.com/elastic/golang-crossbuild/issues/457

Update pull-requests.json to skip CI in some cases

---

NPCAP.md

Doing this for obvious reasons, it didn't occur to me that packetbeat also cared about the explicit NPCAP version, so adding a bit to the docs here.

Update NPCAP docs to mention packetbeat magefile

---

.buildkite/pipeline.yml
.github/updatecli.d/bump-go-release-version.sh
README.md
go/Makefile.common
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

Create images that use the [microsoft/go](https://github.com/microsoft/go) toolchain instead of the upstream go one so that crossbuild images can be used in order to make FIPS compliant binaries.
FIPS images can be created by setting `FIPS=true`, i.e.:
```sh
FIPS=true make -C go -f Makefile.debian11 build
```
Images will have their tag extension end in `-fips`

Add FIPS env var to build crossbuild images for FIPS compliance

---

.github/release-drafter.yml
README.md

https://github.com/elastic/golang-crossbuild/pull/504 removed the support, let's udpate the docs so we avoid misleading consumers

docs: update references for ppc

---

catalog-info.yaml

ci(buildkite): let the robots team to run builds through the UI

---

.buildkite/scripts/buildx.sh

For 'docker build buildx' add '--progress=plain' to the arguments
to prevent redrawing of the output which makes it difficult to interpret
the output when viewing CI logs.
It also disables color which makes log output easier to read.

feat(.buildkite/scripts/buildx.sh): use --progress=plain

---

go/Makefile.common

The version wasn't updated by https://github.com/elastic/golang-crossbuild/pull/550

Update version in Makefile.common

---

go/Makefile.common

`1.24.0` version was not updated in the Makefile.
I think that's related to some updates in the version of the updatecli introduced in https://github.com/elastic/golang-crossbuild/pull/470

bump 1.24.0 version

---

.buildkite/pipeline.yml

See https://github.com/elastic/golang-crossbuild/blob/main/NPCAP.md#backports
There is the concept of `major.minor.patch.x` for cases that need to change an existing Golang Crossbuild release with something else. 
We have used that in some cases such as the NPCAP in the past, and recently at https://github.com/elastic/golang-crossbuild/pull/554
But the existing conditions in the BK pipeline didn't allow to actually proceed.
In my view, we should allow running releases for:
- main
- ^[0-9]+.[0-9]+$
- ^[0-9]+.[0-9]+
This should help with cases such as:
- `main`
- `1.24`
- `1.24.0.x`

buildkite: support for npcap releases or urgency releases

---

.buildkite/pipeline.yml
Makefile.common
go/Makefile.debian10
go/Makefile.debian11
go/Makefile.debian12
go/base-arm/Dockerfile.tmpl
go/base-arm/sources-debian10.list
go/base-arm/sources-debian11.list
go/base-arm/sources-debian12.list
go/base-arm/sources-debian9.list
go/base/Dockerfile.tmpl
go/darwin-arm64/Dockerfile.tmpl
go/darwin-arm64/rootfs/compilers.yaml
go/darwin/Dockerfile.tmpl

Reverts elastic/golang-crossbuild#559
Re-push 1.24.0 images to allow 9.0.0-rc1 DRAs re-release as 9.0.0

Revert "ci: split debian 11 amd/arm (backport #533)"

---

go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

Strip static coded microsoft/go prerelease identifier from download.
The microsoft/go toolchain may include separate patches (from upstream) that are designated with a prerelease identifier, i.e., `v1.24.1-1` or `v1.24.1-2` (note: the current microsoft/go patches to `v1.24.1` only change their test infrastructure and not the binary).
Release are listed in their github: https://github.com/microsoft/go/releases
Not using a pre-release identifier uses the latest available one (this is consistent with how we gather the SHA256 checksums).

Strip microsoft/go pre-release identifier

---

.github/actions/bump-golang/action.yml
.github/updatecli.d/bump-go-microsoft-version.sh
.github/updatecli.d/bump-microsoft.yml
go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

Support patch security versions for the Microsoft golang:
- https://github.com/elastic/golang-crossbuild/pull/565#issuecomment-2767102516
Otherwise, we won't be able to create a golang crossbuild docker image with the latest Microsoft golang version. Bear in mind, we use major.minor.patch format.
When I ran
```bash
$ 
GO_MINOR=1.24 GITHUB_TOKEN=$(gh auth token) \
GITHUB_ACTOR=v1v BRANCH=test/my-previous-version \
updatecli apply --config .github/updatecli.d/
```
It created https://github.com/v1v/golang-crossbuild/pull/8
```
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline ".github/updatecli.d/bump-go-microsoft-version.sh"
Loading Pipeline ".github/updatecli.d/bump-go-release-version.sh"
Loading Pipeline ".github/updatecli.d/bump-golang.yml"
Loading Pipeline …
```

updatecli: microsoft security patches

---

.github/updatecli.d/bump-go-microsoft-version.sh

Fixes a regression after merging https://github.com/elastic/golang-crossbuild/pull/565 and resolving the conflicts in https://github.com/elastic/golang-crossbuild/pull/566

updatecli: support empty arg

---

.github/actions/bump-golang/action.yml

Reverts elastic/golang-crossbuild#470
I think this is causing some issues when force-update happens and some commits are lost.

Revert "build(deps): bump the github-actions group across 1 directory with 2 updates"

---

.github/updatecli.d/bump-golang.yml

This should help when the assets.json is not available.
Closes https://github.com/elastic/golang-crossbuild/issues/571
```bash 
$ GO_MINOR=1.24 GITHUB_TOKEN=$(gh auth token) \
GITHUB_ACTOR=v1v BRANCH=main \
updatecli apply --config .github/updatecli.d/bump-golang.yml
```
```
condition: condition#is-not-available
--------------------------
✗ condition on file ["https://aka.ms/golang/release/latest/go1.24.2.assets.json"] passed
condition: condition#dockerTag
-------------------
✔ docker image golang:1.24.2 found
condition: condition#is-already-updated
----------------------------
The shell 🐚 command "/bin/sh /var/folders/t7/ghqdh8cx2g12pwb_w0ncmw900000gn/T/updatecli/bin/930c7a665b94254478ed7050ad905da920eb37a219b5e35b90beba13d0afcab2.sh" ran successfully with the following output:
----
---- …
```

updatecli: add condition for assets.json

---

.github/release-drafter.yml
README.md
go/Makefile.debian12
go/ppc/.dockerignore
go/ppc/Dockerfile.tmpl
go/ppc/Makefile
go/ppc/rootfs/compilers.yaml
go/ppc/rootfs/helloWorld.c

This reverts https://github.com/elastic/golang-crossbuild/pull/504 and https://github.com/elastic/golang-crossbuild/pull/513
Closes https://github.com/elastic/golang-crossbuild/issues/580

Revert "Remove building ppc (#504) (#513)"

---

catalog-info.yaml

https://github.com/elastic/golang-crossbuild/pull/299/ create the foundations but, `1.24` or any other `major.minor` branches should not be cancelled if a new merge commit is merged.
https://buildkite.com/elastic/golang-crossbuild/builds/1000#0196107a-e646-476b-aac1-a1d86ea07735

bk: stop cancelling any builds for the `1.*` golang branches

---

go/base-arm/Dockerfile.tmpl
go/base/Dockerfile.tmpl

See https://github.com/microsoft/go/releases/v1.24.2-2
---
<Actions>
<action id="a97e8ebb0cd2b13f0766a495c3fbbf8f0cf983259470b64e31d1a4f81842ab89">
<h3>Bump golang-microsoft to latest version</h3>
<details id="226c7073ca2786d439fbbe0bf13d2b5523040d4801dfca93d49ece1280917dd3">
<summary>Update go version 1.24.2-2</summary>
<p>ran shell command &#34;.github/updatecli.d/bump-go-microsoft-version.sh 1.24.2-2&#34;</p>
<details>
<summary>1.24.2-2</summary>
<pre>&#xA;Release published on the 2025-04-17 18:13:11 +0000 UTC at the url https://github.com/microsoft/go/releases/tag/v1.24.2-2&#xA;&#xA;Microsoft build of Go v1.24.2-2&#xD;&#xA;&#xD;&#xA;No changes since v1.24.2-1. This release was run to test infrastructure changes end to end.</pre>
</details>
</details>
</action>
</Actions>
---
<table> …

[Automation] Bump Microsoft version to 1.24.2-2

---

.github/updatecli.d/bump-microsoft.yml

Needs conditionals to avoid [failing](https://github.com/elastic/golang-crossbuild/actions/runs/14769064076/job/41465887703) when the PR has already raised.
See https://github.com/elastic/golang-crossbuild/actions/runs/14774735610/attempts/1 if no PR but required changes
```
⚠ Bump golang-microsoft to latest version:
Source:
✔ [latestGoVersion] Get Latest Go Release
✔ [minor] Get minor version
✔ [securityVersion] Get security version
Condition:
✔ [is-already-updated] Is security version '-2' not updated in 'go/base/Dockerfile.tmpl'?
Target:
⚠ [update-go-versions] Update go version 1.24.2-2
```
See https://github.com/elastic/golang-crossbuild/actions/runs/14774735610/attempts/2 if PR exists with the required changes
```
Bump golang-microsoft to latest version - default …
```

updatecli: add conditions for the security version

---

.github/updatecli.d/bump-go-microsoft-version.sh
.github/updatecli.d/bump-go-release-version.sh
.github/updatecli.d/bump-golang.yml
.github/updatecli.d/bump-microsoft.yml

There are two updatecli pipelines:
1) For bumping the golang version (major.minor.patch approach)
2) For bumping the security version.
I still need to figure out how to avoid some issues we have with some errors when the PR exists. But for now I'll merge this PR

updatecli: run bump-golang and bump-go-microsoft independent

---

.buildkite/pipeline.yml
.github/release-drafter.yml
Makefile
README.md
go/Makefile.debian7
go/Makefile.debian8

Notifies https://github.com/elastic/apm-server/pull/16849
So we can release `7.17` that still uses `debian-7`:
- https://github.com/elastic/beats/blob/a156701b0302ca0e4e8676d2de96ebf2c1b7879d/dev-tools/mage/crossbuild.go#L222-L225

Revert "stop publishing debian7 and debian8 from 1.23.7 onwards (#510)"

---

.buildkite/fpm-pipeline.yml
.buildkite/hooks/pre-command
.buildkite/llvm-apple-pipeline.yml
.buildkite/pipeline.yml
.buildkite/scripts/build.sh
.buildkite/scripts/changeset/fpm
.buildkite/scripts/changeset/llvm-apple
.buildkite/scripts/common.sh
.buildkite/scripts/llvm-apple/build.sh
.buildkite/scripts/llvm-apple/publish.sh
.buildkite/scripts/llvm-fpm/build_and_publish.sh
.buildkite/scripts/post-release.sh
catalog-info.yaml

* Use monorepo-diff.
* Use bk pipeline upload instead of triggering to help with a centralised GH status comment.
* Fix apple pipeline to use the Google auth.
* Use [log groups](https://buildkite.com/docs/pipelines/configure/managing-log-output#collapsing-output)
I don't know the reason for not using the `monorepo-diff`, but as far as I see:
1) BK pipelines for LLM or apple are not running in `main` <--- I'm not sure whether we want this or not.
2) BK pipelines for LLM or apple are not running on PRs when changing some of the changeset files:
- https://github.com/elastic/golang-crossbuild/pull/610 <-- changed the bk pipeline definitions.
This PR should help apply what we applied in Elastic Agent a few months ago to use the bk-agent upload and the monorepo diff.
- does monorepo-diff work …

bk: use monorepo-diff

---

.buildkite/pipeline.yml

This should avoid situations when targetting a different branch will run the FPM or llvm-apple pipelines.

bk: only if targeting main

---

.buildkite/pipeline.yml
.github/release-drafter.yml
Makefile
README.md
go/Makefile.debian7

Beats 7.17 has no further planned releases, but we must remain ready for potential emergency patches.
Given this policy, we also aim to keep up with newer Go versions. PR #510 removed debian7 and debian8 images, causing failures when we upgraded 7.17 to go1.24.3. We cannot migrate to debian 9-11 due to glibc 2.13 constraints.
That said, restore the debian7 images to fix our 7.17 builds.
Relates https://github.com/elastic/beats/pull/43984.

Restore debian7 images needed for beats 7.17

---

.github/release-drafter.yml

I ran 
```bash
$ crane ls  docker.elastic.co/beats-dev/golang-crossbuild 
| grep 1.24.4
1.24.4-armel-debian12-fips
1.24.4-armel-debian12
1.24.4-armhf-debian10-fips
1.24.4-armhf-debian10
1.24.4-armhf-debian11-fips
1.24.4-armhf-debian11
1.24.4-armhf-debian12-fips
1.24.4-armhf-debian12
1.24.4-armhf-debian9-fips
1.24.4-armhf-debian9
1.24.4-armhf-fips
1.24.4-armhf
1.24.4-base-arm-debian10-fips
1.24.4-base-arm-debian10
1.24.4-base-arm-debian11-fips
1.24.4-base-arm-debian11
1.24.4-base-arm-debian12-fips
1.24.4-base-arm-debian12
1.24.4-base-arm-debian9-fips
1.24.4-base-arm-debian9
1.24.4-base-debian10-fips
1.24.4-base-debian10
1.24.4-base-debian11-fips
1.24.4-base-debian11
1.24.4-base-debian12-fips
1.24.4-base-debian12
1.24.4-base-debian7-fips
1.24.4-base-debian7
1.24.4-base-debian9-fips …
```

docs: update the list of containers

---

.buildkite/pipeline.yml
Makefile
README.md
go/Makefile.debian8
go/base-arm/Dockerfile.tmpl
go/base-arm/sources-debian8.list

Reintroduce support for golang 1.24 on debian 8 as it is needed by https://github.com/elastic/beats/pull/43984. Respective BK failure on beats https://buildkite.com/elastic/filebeat/builds/18906#01977d68-385f-4569-9f98-216d839be34a/157-231

Reintroduce debian8 publishing for go 1.24

---

.github/updatecli.d/bump-go-microsoft-version.sh
.github/workflows/bump-golang-previous.yml
.github/workflows/bump-golang.yml

This commit fixes the Goland bump GH action in the 1.23 branch which is failing due to a missing script.
This was the failure observed: https://github.com/elastic/golang-crossbuild/actions/runs/15723702898/job/44309400069#step:3:349

Fix bump MS Golang bump in 1.23
