README.md
Update README.md regarding the release process automation
Caused by https://github.com/elastic/golang-crossbuild/issues/54
=> DOCS: add CI build badge

Makefile, go1.10/Makefile.debian9, go1.11/Makefile.debian9, go1.12/Makefile.debian9, go1.13/Makefile.debian9, go1.14/Makefile.debian9
=> Add support to create debian9 images

README.md, go1.14/Makefile.common, go1.14/base/Dockerfile.tmpl
Changes to latest 1.14 for compiler fixes
=> Update golang to 1.14.15

Jenkinsfile, README.md, go1.15/Makefile.common, go1.15/base-arm/Dockerfile.tmpl, go1.15/base/Dockerfile.tmpl
It will break because the version has not been released yet.
=> Update Golang to 1.15.9

Jenkinsfile, README.md, go1.16/Makefile.common, go1.16/base-arm/Dockerfile.tmpl, go1.16/base/Dockerfile.tmpl
=> Update golang 1.16.x to latest patch version

go1.16/base/Dockerfile.tmpl
some Python essencial modules
related to https://github.com/elastic/golang-crossbuild/issues/92
=> fix: add python basic modules

go1.15/Makefile.debian9, go1.15/arm/Dockerfile.tmpl, go1.15/armel/.dockerignore, go1.15/armel/Dockerfile.tmpl, go1.15/armel/Makefile, go1.15/armel/rootfs/compilers.yaml, go1.15/armel/rootfs/helloWorld.c, go1.15/armhf/.dockerignore, go1.15/armhf/Dockerfile.tmpl, go1.15/armhf/Makefile, go1.15/armhf/rootfs/compilers.yaml, go1.15/armhf/rootfs/helloWorld.c, go1.15/base/Dockerfile.tmpl, go1.15/main/Dockerfile.tmpl, go1.15/mips/Dockerfile.tmpl, go1.15/ppc/Dockerfile.tmpl, go1.15/s390x/Dockerfile.tmpl
feat: precompile libpcap for Go 1.15
follow up of https://github.com/elastic/golang-crossbuild/pull/91
=> feat: precompile libpcap for Go 1.15

go1.15/Makefile.common, go1.16/Makefile.common
- Relates https://github.com/elastic/beats/issues/26182
=> Update version tags

.ci/bump-go-release-version.sh
There are two kind of docker base images:
- amd64
- arm64
=> Support arm64 and amd64 sha validations

go1.16/main/Dockerfile.tmpl
this PR adds the same libraries we have in other architectures to the x86 architectures.
=> fix: add libs to x86 Docker images

Jenkinsfile
=> CI: add traces for the post-release

.ci/scripts/release-notes.sh
Generate the right changelog contain
```
$ .ci/scripts/release-notes.sh                                                        
Getting gren config from local file /Users/vmartinez/work/src/github.com/elastic/golang-crossbuild/.grenrc.js
🤖  - Generate changelog file:
===================================
✔ Releases found: 1
✔ Changelog created in /Users/vmartinez/work/src/github.com/elastic/golang-crossbuild/CHANGELOG.md
$ cat CHANGELOG.md
- `docker.elastic.co/beats-dev/golang-crossbuild:1.17.5-arm` - linux/arm64
- `docker.elastic.co/beats-dev/golang-crossbuild:1.17.5-armel` - linux/armv5, linux/armv6
- `docker.elastic.co/beats-dev/golang-crossbuild:1.17.5-armhf` - linux/armv7
- `docker.elastic.co/beats-dev/golang-crossbuild:1.17.5-base`
- …
```
=> Changelog generation to pick up releases

LICENSE
Theses images are used to cross build binaries in multiples projects.
Closes #120
=> Add Apache license 2 to the repository.

.ci/fpm.groovy, .ci/jobs/fpm-mbp.yml
It adds a job to build the FPM Docker image
=> feat: job to build/push fpm docker images

.ci/jobs/folders.yml, .ci/jobs/llvm-apple-mbp.yml, .ci/llvm-apple.groovy, go/llvm-apple/Dockerfile.tmpl, go/llvm-apple/Makefile
It adds a new job to compile the LLVM Apple version and push the Docker image
=> feat: job to compile the LLVM Apple version

.ci/jobs/fpm-mbp.yml, .ci/jobs/llvm-apple-mbp.yml
disable default PR notifications
=> chore: disable default PR notifications

.ci/jobs/fpm-mbp.yml, .ci/jobs/golang-crossbuild-mbp.yml, .ci/jobs/llvm-apple-mbp.yml, Jenkinsfile
* [fix: move header to the first line](https://github.com/elastic/golang-crossbuild/commit/b4ccc6b3bbdd367a2fa1469465a8a3d05a6998c9)
* [feat: filter branches](https://github.com/elastic/golang-crossbuild/commit/88ccf2b4d62dde44566e12a819f76807edfc5b56)
=> fix: move header to the first line

Jenkinsfile
List staging and release docker images
=> ci: docker image table for generated images

.ci/fpm.groovy, .ci/llvm-apple.groovy
* [fix: increase timeout](https://github.com/elastic/golang-crossbuild/commit/6a042696a58319615b8462db29d6ad64d1e60435)
* [feat: add new valid triggers](https://github.com/elastic/golang-crossbuild/commit/08b25a642ce1f96702cd99d3bdc40d348990f0e1)
=> fix: Increase timeout

go/llvm-apple/Makefile
fix: remove echo from the push command
=> fix: remove echo from the push command

go/arm/Dockerfile.tmpl, go/armel/Dockerfile.tmpl, go/armhf/Dockerfile.tmpl, go/base/Dockerfile.tmpl, go/darwin-arm64/Dockerfile.tmpl, go/darwin/Dockerfile.tmpl, go/main/Dockerfile.tmpl, go/mips/Dockerfile.tmpl, go/mips32/Dockerfile.tmpl, go/ppc/Dockerfile.tmpl, go/s390x/Dockerfile.tmpl
it adds trim to all `{{if}}` flow sentences, this removes unwanted whitespace in the final Dockerfile
=> chore: trim if in templates

.ci/fpm.groovy
Use the staging repository to push Docker images in PRs
=> fix: stage FPM images on PRs

.ci/scripts/buildx.sh, go/arm/Dockerfile.tmpl, go/arm/Makefile, go/base/Makefile
build arm64 Docker image for amd64/arm64
depends on https://github.com/elastic/golang-crossbuild/pull/197
=> feat: build arm64 Docker image for amd64/arm64

.ci/llvm-apple.groovy
* set timeout for the LLVM Apple job
* rename the matrix stage
* Push Docker images 🤦
=> chore: set timeout for the LLVM Apple job

.github/workflows/bump-golang-1.18.yml, .github/workflows/bump-golang-1.19.yml, .github/workflows/bump-golang.yml, .github/workflows/opentelemetry.yml
* use opentelemetry exporter
* change names
* fix relative path with composite actions
=> action: fix relative path

.ci/bump-golang.yml, .mergify.yml
Enable auto-merge with updatecli and mergify
Honour the title field in the right location
=> updatecli: auto-merge and override title

.ci/bump-golang.yml, .mergify.yml
Enable auto-merge with mergify and tag the PRs with the right label so the delete branches can work in mergify
The existing CI validates the docker images are healthy with some sanity checks, hence it's possible to use the merge queue with Mergify
=> mergify automation

go/base-arm/sources-debian9.list, go/base/sources-debian9.list
Closes https://github.com/elastic/golang-crossbuild/issues/291
=> fix debian9 support

.buildkite/pull-requests.json, catalog-info.yaml
In terms of impementation of [1695](https://github.com/elastic/ingest-dev/issues/1695):
1. Updated pull-request.json
2. Temporarily disabled branch filtering in catalog-info.yml 
3.  Enabled push_commit_status in catalog-info.yml
=> 1695: Update infrastructure for golang-crossbuild BK pipelines

.buildkite/pipeline.yml, catalog-info.yaml
1. Updated branch filtering to run on only on main & release branches
2. Removed matrix for ARM, since other Debian usage is not planned
=> Updated branch filtering and removed matrix

.buildkite/hooks/pre-command, .buildkite/pipeline.yml
Added GCS secret for "Release" and "Post-Release" steps in re-command script.
=> Updated pre-command script

.buildkite/hooks/pre-command
Added docker login in pre-command for release steps
=> Added docker login for release steps

.buildkite/hooks/pre-command
Changed post release step key in pre-command script
=> Updated post-release step key

.buildkite/hooks/pre-exit, README.md
Updated Readme.md build badge address to Buildkite
=> Add Buildkite build badge

.github/workflows/opentelemetry.yml
Part of the Observability for the CI/CD
=> github-action: listen for all the workflow runs

.github/actions/bump-golang/action.yml
=> updatecli: fix location of the file

.buildkite/scripts/buildx.sh
as explained in the docs
See https://docs.docker.com/build/building/multi-platform/\#install-qemu-manually
=> use tonistiigi/binfmt without a tag

.buildkite/pipeline.yml, Makefile.common, go/Makefile.debian10, go/Makefile.debian11, go/Makefile.debian12, go/base-arm/Dockerfile.tmpl, go/base-arm/sources-debian10.list, go/base-arm/sources-debian11.list, go/base-arm/sources-debian12.list, go/base-arm/sources-debian9.list, go/base/Dockerfile.tmpl, go/darwin-arm64/Dockerfile.tmpl, go/darwin-arm64/rootfs/compilers.yaml, go/darwin/Dockerfile.tmpl
Reverts elastic/golang-crossbuild#561
=> Revert "Revert "ci: split debian 11 amd/arm (backport #533)""

.buildkite/pipeline.yml, Makefile.common, go/Makefile.debian10, go/Makefile.debian11, go/Makefile.debian12, go/base-arm/Dockerfile.tmpl, go/base-arm/sources-debian10.list, go/base-arm/sources-debian11.list, go/base-arm/sources-debian12.list, go/base-arm/sources-debian9.list, go/base/Dockerfile.tmpl, go/darwin-arm64/Dockerfile.tmpl, go/darwin-arm64/rootfs/compilers.yaml, go/darwin/Dockerfile.tmpl
Reverts elastic/golang-crossbuild#562
=> Revert "Revert "Revert "ci: split debian 11 amd/arm (backport #533)"""

.buildkite/pipeline.yml, Makefile.common, go/Makefile.debian10, go/Makefile.debian11, go/Makefile.debian12, go/base-arm/Dockerfile.tmpl, go/base-arm/sources-debian10.list, go/base-arm/sources-debian11.list, go/base-arm/sources-debian12.list, go/base-arm/sources-debian9.list, go/base/Dockerfile.tmpl, go/darwin-arm64/Dockerfile.tmpl, go/darwin-arm64/rootfs/compilers.yaml, go/darwin/Dockerfile.tmpl
Reverts elastic/golang-crossbuild#563
=> Revert "Revert "Revert "Revert "ci: split debian 11 amd/arm (backport #533)""""

.buildkite/pipeline.yml
This should help with the environmental flakiness
=> bk: add retry

README.md
Leftover from https://github.com/elastic/golang-crossbuild/pull/456
=> update docs for mips

.github/actions/bump-golang/action.yml
https://github.com/elastic/oblt-actions/tree/v1/updatecli/run-and-notify
Then we don't need PRs like https://github.com/elastic/golang-crossbuild/pull/493
=> updatecli: use the oblt-actions

.buildkite/hooks/pre-command
=> bk: remove unused secret access

.buildkite/fpm-pipeline.yml, .buildkite/hooks/pre-command, .buildkite/hooks/pre-exit, .buildkite/llvm-apple-pipeline.yml, .buildkite/pipeline.yml, .buildkite/scripts/build.sh
See https://github.com/elastic/elastic-agent/pull/8444
Avoid the pattern of login with the pre-command and use the declarative plugin usage int he steps that require the login.
=> bk: use docker login plugin
